name: alice_manager
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.0.2
homepage: https://github.com/DexJoke/alice-manager
repository: https://github.com/DexJoke/alice-manager
topics:
  - dio
  - interceptor
  - get x

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: 9.9.1
  rxdart: ^0.27.7
  path_provider: ^2.0.9
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0
  sensors_plus: ^1.4.1
  share_plus: 7.2.2
  collection: ^1.18.0
  url_launcher: 6.3.0
  equatable: ^2.0.5
  get: 4.6.6
  dio: 5.5.0+1
  draggable_float_widget: 0.1.0


dev_dependencies:
  flutter_lints: ^4.0.0